image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - "ms-python.python"
    - "littlefoxteam.vscode-python-test-adapter"
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
