image:
  file: .gitpod.Dockerfile
tasks:
    - command: |
        pip install pytest-playwright
        playwright install

vscode:
  extensions:
    - "ms-python.python"

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
