image:
  file: .gitpod.Dockerfile
tasks:
    - command: |
        pip install pytest-playwright
        playwright install
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
